#MQTT Broker address
# mqtt_broker_address: "0.0.0.0"
# mqtt_broker_port: 1883
# mqtt_user: "guest"
# mqtt_password: "guest"
mqtt_broker_address: "52.77.234.153"
mqtt_broker_port: 30006
mqtt_user: ""
mqtt_password: ""

#MQTT topics
mqtt_navigation_topic: "nus5gdt/robots/unitree/navigate"
mqtt_robot_state_topic: "nus5gdt/robots/unitree/robot_state"

#ROS Topics
ros_start_navigation_topic:  "robot_goal"
ros_cancel_navigation_topic:  "cancel_goal"
ros_position_topic:  "robot_position"